// lib/projectsData.js

export const allProjects = [
  { title: "Residential Rooftop – 3 kW", description: "Installed in Jaipur, powering a full household.", img: "/projects/p1.jpg" },
  { title: "Residential Unit at Sikar – 5 kW", description: "Always Electricity On – Worry Gone.", img: "/projects/p2.jpg" },
  { title: "Industrial Roof – 50 kW", description: "Factory solar solution in Gujarat, cutting bills by 70%.", img: "/projects/p3.jpg" },
  { title: "Portable Solar Solution for Villages – 2.0 kW", description: "Solar project for remote rural sectors in Rajasthan.", img: "/projects/p4.jpg" },
  { title: "Industrial Solar Solution at Jaipur – 15 kW", description: "Reliable backup & savings for a rural hospital.", img: "/projects/p5.jpg" },
  { title: "Commercial Mall – 30 kW", description: "Installed on shopping mall rooftop.", img: "/projects/p6.jpg" },
  { title: "Factory Warehouse Solar – 20 kW", description: "Warehouse installation with net-metering.", img: "/projects/p7.jpg" },
  { title: "Village House Naryana ka Bass – 5 kW", description: "Solar electrification for rural house.", img: "/projects/p8.jpg" },
  { title: "Water Pump for Fields – 5 HP", description: "Solar water pump solution in Churu.", img: "/projects/p9.jpg" },
  { title: "College Campus – 35 kW", description: "Sustainable energy for college campus.", img: "/projects/p10.jpg" },
  { title: "Residential Villa – 7 kW", description: "Luxury villa solar with hybrid inverter.", img: "/projects/p11.jpg" },
  { title: "Textile Unit – 40 kW", description: "Solar for industrial textile unit, saving 60%.", img: "/projects/p12.jpg" },
  { title: "Petrol Pump – 12 kW", description: "Petrol pump running on solar during daytime.", img: "/projects/p13.jpg" },
  { title: "Farm House – 18 kW", description: "Farm House Project with rooftop solar.", img: "/projects/p14.jpg" },
  { title: "Hospital at Sikar – 12 kW", description: "Powering ICU Facility.", img: "/projects/p15.jpg" },
  { title: "Village Project at Khudi-bari – 12 kW", description: "Solar for Agri Field Project.", img: "/projects/p16.jpg" },
  { title: "Vegetable & Fruits Cold Room at Sikar – 5 kW", description: "Solar backup for farm cold storage.", img: "/projects/p17.jpg" },
  { title: "E-Mart's Office – 30 kW", description: "Reducing energy costs for IT firm.", img: "/projects/p18.jpg" },
  { title: "Apartment Complex – 45 kW", description: "Housing society solar rooftop.", img: "/projects/p19.jpg" },
  { title: "Tehsil Lachhmangarh House – 10 kW", description: "Leading Businessman's house empowered with net-metering system.", img: "/projects/p20.jpg" },
  { title: "Roof Top Solar at Home - 10 KW", description: "Installed at Sardarshar, Churu.", img: "/projects/p21.jpg" },
  { title: "House Roof Project – 10 kW", description: "House site at Churu powered fully by clean solar energy.", img: "/projects/p22.jpg" },
  { title: "Hotel Sunshine's Solar Servicing – 10 kW", description: "Luxury hotel's solar servicing with reasonable costs.", img: "/projects/p23.jpg" },
  { title: "Shop Roof top Solar, Rajgarh – 8 kW", description: "Smart solar energy powering shop.", img: "/projects/p24.jpg" },
  { title: "Home Rooftop Solar – 5 kW", description: "Regular Electricity units to renewable energy.", img: "/projects/p25.jpg" },
  { title: "Solar at commercial shop at Jhunjhnu – 12 kW", description: " Full power generation .", img: "/projects/p26.jpg" },
  { title: "Providing Services at Cold Storage Unit – 10 kW", description: "Servicing for solar storage facility in Sikar.", img: "/projects/p27.jpg" },
  { title: "Providing Services at Urban Apartment Tower – 10 kW", description: "Modern apartment using solar for common utilities.", img: "/projects/p28.jpg" },
  { title: "Community Center – 52 kW", description: "Empowering rural community gatherings sustainably.", img: "/projects/p29.jpg" },
  { title: "Smart House Project – 25 kW", description: "Solar electrification using solar energy.", img: "/projects/p30.jpg" },
  { title: "C.A. House  – 10 kW", description: "House building reducing electricity costs.", img: "/projects/p31.jpg" },
  { title: "Solar Services – 5 kW", description: "Service Providing for Solars.", img: "/projects/p32.jpg" },
  { title: "Dairy Unit – 10 kW", description: "Solar-powered refrigeration for rural dairy unit.", img: "/projects/p33.jpg" },
  { title: "Mid Scale Hospital Extension Wing – 15 kW", description: "Supporting power backup for medical operations.", img: "/projects/p34.jpg" },
  { title: "City Apartment Cluster – 30 kW", description: "Solar power for multi-block housing society.", img: "/projects/p35.jpg" },
  { title: "House hold Work-Shop – 15 kW", description: "Energy-efficient solar setup for housing unit.", img: "/projects/p36.jpg" },
  { title: "Private School – 15 kW", description: "Solar system ensuring 24-hour energy supply for Private school.", img: "/projects/p37.jpg" },
  { title: "Roof top Solar at Factory, Sikar – 30 kW", description: "Empowering industries with renewable energy.", img: "/projects/p38.jpg" },
  { title: "Solar Energy Plant – 12 kW", description: "Solar for Daily Electricity Requirements.", img: "/projects/p39.jpg" },
  { title: "Warehouse Hub – 35 kW", description: "Energy-efficient logistics and warehouse unit.", img: "/projects/p40.jpg" },
];
